### PR TITLE
Get basic UI working and refactor transport modes

### PR DESCRIPTION
**Pull request by ghost**
Bunch of stuff in this PR that I'd appreciate review on.

This was a bit rushed but I've done the following:
- Update Rails
- Update other gems
- Removed Angular from the manifest
- Refactored the transport modes into actual database models
- Got basic UI working with just some jQuery
- Setup puma for Heroku

You can test it out here: https://rerouteit.herokuapp.com/

I've still got to write the tests for the `TripService`.

### CODE REVIEW

**Comment by ghost** [comment]
To test this branch locally you'll need to setup the database: `rake db:migrate db:seed`.

**Comment by cdaloisio** [comment]
Thanks @Soliah! It's been a hectic end to the year but I'll be going through this shortly, thanks for your contributions! :smile:

**Comment by cdaloisio** [comment]
Happy New Year @Soliah! Apologies for the delay, it has been a hectic break :smile: 

Looks good, the only thing I would say is to perhaps convert the JS to coffee-script because the `coffee-rails` gem installed

I'll be merging this early in the week and working on implementing the other remaining methods of cost and calories

**Comment by ghost** [comment]
looks good .. there are a few things i would do differently. 
But the important thing that it works and validations in
place. @Soliah good job.

**Comment by ghost** [comment]
@arvindcj thanks. This was more just to get something working and the project moving a bit.

**Pull request closed without merging**
