### PR TITLE
Style enforcement and CI

### PR DESCRIPTION
**Pull request by ghost**
I'd recommend that you guys setup a style guide and lean on something like https://houndci.com for enforcing style, as I can already see in #14 inconsistencies in spacing, `"` and `'` etc

I'd also recommend using like https://travis-ci.org for CI. Both of these services are free for open source.

Lastly, http://codeclimate.com/ is amazing and is also free for open source.

### CODE REVIEW

**Comment by ghost** [comment]
I'll try and send a PR for this tonight.

**Comment by cdaloisio** [comment]
:+1:

**Comment by ghost** [comment]
https://codeclimate.com/github/CodeforAustralia/rerouteit can be setup without additional permissions, but Travis and Hound need collaborator access.

@cdaloisio can you set them up?

**Comment by ghost** [comment]
[Dependency Status](https://gemnasium.com/CodeforAustralia/rerouteit)

[Code Climate](https://codeclimate.com/github/CodeforAustralia/rerouteit)

[Test Coverage](https://codeclimate.com/github/CodeforAustralia/rerouteit)

**Comment by ghost** [comment]
I've added the badges based on conventions, but obviously Travis isn't hooked up properly as I don't have access.

**Comment by ghost** [comment]
@cdaloisio Travis will need to be setup by a collaborator. CodeClimate also requires a collaborator for test coverage.

**Comment by cdaloisio** [comment]
@Soliah Not a problem, I've set these up. Should be good to go. There is just an issue with the first build which I'll get sorted soon. I'm just going through #14 to split it into separate pull requests and make a few adjustments

**Comment by ghost** [comment]
@cdaloisio ah we need to also do a `bundle exec rake db:create` in the `before_script` section of the travis.yml

**Comment by cdaloisio** [comment]
Yep, just about to add it :+1:

**Pull request merged**
